### ISSUE TITLE
breaks on arc 5.9

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc-example-ws#5]
```
 Started HTTP "server" @  http://localhost:3333
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\WINDOWS\\system32\\cmd.exe',
  path: 'C:\\WINDOWS\\system32\\cmd.exe',
  spawnargs: [
    '/d',
    '/s',
    '/c',
    `"node -e "let fn = require('./index').handler;let event = ` +
      'JSON.parse(process.env.__ARC_REQ__);function callback(err, result) { ' +
      ' let payload = err? {name:err.name, message:err.message, ' +
      "stack:err.stack} : result;  console.log('__ARC__', " +
      'JSON.stringify(payload));}var context = {  succeed(x) {    ' +
      'callback(null, x)  },  fail(x) {    callback(x)  }};if ' +
      "(fn.constructor.name === 'AsyncFunction') {  fn(event, context, " +
      'callback).then(function win(result) {    callback(null, result);  ' +
      '}).catch(callback);}else {  fn(event, context, callback);}""'
  ]
}
```

See https://github.com/architect/architect/issues/392

**Comment by boldenburg** [comment]
I have a PR for the `arc-example-ws` repo that I'm waiting to submit that updates the code to the latest version of arc that is blocked by merging https://github.com/architect/architect/pull/383 that should resolve these issues. Please note that this example repo is only tested working with 5.7.0.

**Comment by mikemaccana** [comment]
Ah gotcha, thanks for responding @boldenburg!

**Comment by brianleroux** [comment]
I was under the impression it was but just testing and its completely broken so I'm going to fix now. Sorry about this.

**Comment by brianleroux** [comment]
should be fixed for real this time in `+ @architect/architect@5.9.16` but I only did a basic hello world runthru so pls let me know if you find more issues!
